export const cardsData = [
  {
    id: 1,
    title: "Task 1",
    date: "26/9/2022 11:07hs",
    creator: "Julio Avant",
    type: "new",
    priority: "high",
    description: "Lorem ipsum dolor sit amet, consectetur adip",
  },
  {
    id: 2,
    title: "Task 2",
    date: "24/9/2022 14:07hs",
    creator: "Santiago Rensonnet",
    type: "inProcess",
    priority: "high",
    description: "Fake description",
  },
  {
    id: 3,
    title: "Task 3",
    date: "21/9/2022 12:07hs",
    creator: "Ivan Dujaut",
    type: "finished",
    priority: "medium",
    description: "Fake description",
  },
  {
    id: 4,
    title: "Task 4",
    date: "22/9/2022 15:07hs",
    creator: "Cosme Fulanito",
    type: "new",
    priority: "high",
    description:
      "I have lost. Yet from now on you are also dead — dead to the World,dead to Heaven, dead to Hope! In me you lived — and, in my death — see by this face, which is your own, how wholly, how completely,you have killed — yourself!",
  },
  {
    id: 5,
    title: "Task 5",
    date: "13/12/2022 17:07hs",
    creator: "Santiago Rensonnet",
    type: "finished",
    priority: "medium",
    description: "Fake description",
  },
  {
    id: 6,
    title: "Task 6",
    date: "10/9/2022 10:07hs",
    creator: "Ivan Dujaut",
    type: "finished",
    priority: "medium",
    description: 'Quoth the Raven: "Nevermore"',
  },
];
